---

iserver_hostname: alpine3-kvm
iserver_sshkey: ""

iserver_alpine_repos:
  - 'http://nl.alpinelinux.org/alpine/v3.11/main'
  - 'http://nl.alpinelinux.org/alpine/v3.11/community'
  - '@edge http://nl.alpinelinux.org/alpine/edge/main'
  - '@testing http://nl.alpinelinux.org/alpine/edge/testing'
  - '@edgecommunity http://dl-cdn.alpinelinux.org/alpine/edge/community'
