---
- name: Add RPMFusion Free Signing Key for Fedora
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  when: ansible_distribution == 'Fedora'

- name: Add RPMFusion NonFree Signing Key for Fedora
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  when: ansible_distribution == 'Fedora'

- name: Add RPMFusion Free Signing Key for EL9
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-el-9
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add RPMFusion NonFree Signing Key for EL9
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add Microsoft Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add RPMFusion Free Fedora
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPMFusion NonFree Fedora
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add EPEL EL9
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add RPMFusion Free EL9
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add RPMFusion NonFree EL9
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add Microsoft Repo for VSCode
  ansible.builtin.yum_repository:
    name: Microsoft
    description: Microsoft YUM Repo
    state: present
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: Update All Redhat Family Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Fedora Specific Packages
  ansible.builtin.dnf:
    name:
      - discord
      - golang-x-tools-gopls
      - libvirt-devel
      - neofetch
      - pipewire-codec-aptx
      - torbrowser-launcher
    state: latest
  when: ansible_distribution == 'Fedora'


- name: Install Packages on all OS
  ansible.builtin.dnf:
    name:
      - '@Development tools'
      - cargo
      - cmake
      - code
      - curl
      - gnome-tweaks
      - golang
      - lame
      - libtool
      - nmap
      - openssh-server
      - python3-pip
      - tmux
      - vim
      - wget
      - zsh
    state: latest

- name: Install Tiling Window Manager stuff
  ansible.builtin.dnf:
    name:
      - alacritty
      - conky
      - dmenu
      - gnome-screenshot
      - i3-gaps
      - nitrogen
      - picom
      - xrandr
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install Multimedia Codecs
  ansible.builtin.dnf:
    name:
      - ffmpeg
      - gstreamer1-libav
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-free-zbar
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - mpv
      - pavucontrol
      - pavumeter
      - vlc
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install pre-requisite software for DOOM Emacs
  ansible.builtin.dnf:
    name:
      - emacs
      - fd-find
      - ripgrep
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Install pre-requisite software for Suckless Tools
  ansible.builtin.dnf:
    name:
      - fontconfig-devel
      - freetype-devel
      - libX11-devel
      - libXft-devel
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Check if YADM is installed
  ansible.builtin.stat:
    path: /usr/local/bin/yadm
  register: yadm

- name: Install YADM
  ansible.builtin.command: curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm
  when: yadm.stat.exists == False

- name: Make YADM Executable
  ansible.builtin.command: chmod a+x /usr/local/bin/yadm
  when: yadm.stat.exists == False

- name: Make sure openssh server is running
  ansible.builtin.systemd:
    state: started
    name: sshd

- name: Add/Configure user Absenth
  ansible.builtin.user:
    name: absenth
    comment: Absenth 762
    groups: wheel, libvirt
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
