---
- name: Add RPMFusion Free Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Add RPMFusion NonFree Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Add RPMFusion Free
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPMFusion NonFree
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Update All Redhat Family Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Packages on all OS
  ansible.builtin.dnf:
    name: 
      - vim
      - tmux
      - zsh
      - curl
      - wget
      - nmap
      - cargo
      - fd-find
      - ripgrep
      - conky
      - alacritty
      - python3-pip
      - libvirt-devel
      - i3-gaps
      - discord

- name: Check if YADM is installed
  stat:
    path: /usr/local/bin/yadm
  register: yadm

- name: Install YADM 
  ansible.builtin.command: curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm
  when: yadm.stat.exists == False 

- name: Make YADM Executable
  ansible.builtin.command: chmod a+x /usr/local/bin/yadm
  when: yadm.stat.exists == False
