---
- name: Add RPMFusion Free Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Add RPMFusion NonFree Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Add Microsoft Signing Key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add RPMFusion Free
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPMFusion NonFree
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add Microsoft Repo for VSCode
  ansible.builtin.yum_repository:
    name: Microsoft
    description: Microsoft YUM Repo
    state: present
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: Update All Redhat Family Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Packages on all OS
  ansible.builtin.dnf:
    name: 
      - '@Development tools'
      - alacritty
      - cargo
      - cmake
      - code
      - conky
      - curl
      - discord
      - gnome-tweaks
      - golang
      - golang-x-tools-gopls
      - i3-gaps
      - lame
      - libtool
      - nitrogen
      - nmap
      - pipewire-codec-aptx
      - python3-pip
      - ripgrep
      - tmux
      - torbrowser-launcher
      - vim
      - wget
      - xrandr
      - zsh
    state: latest

- name: Install Multimedia Codecs
  ansible.builtin.dnf:
    name: 
      - gstreamer1-libav
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-free-zbar
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - mpv
      - vlc
    state: latest

- name: Install pre-requisite software for DOOM Emacs
  ansible.builtin.dnf:
    name:
      - emacs
      - fd-find
      - ffmpeg
      - libvirt-devel
    state: latest

- name: Install pre-requisite software for Suckless Tools
  ansible.builtin.dnf:
    name: 
      - fontconfig-devel
      - freetype-devel
      - libX11-devel
      - libXft-devel
    state: latest

- name: Check if YADM is installed
  stat:
    path: /usr/local/bin/yadm
  register: yadm

- name: Install YADM 
  ansible.builtin.command: curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm
  when: yadm.stat.exists == False 

- name: Make YADM Executable
  ansible.builtin.command: chmod a+x /usr/local/bin/yadm
  when: yadm.stat.exists == False
