---
- name: Add/Configure user Absenth
  ansible.builtin.user:
    name: absenth
    comment: Absenth 762
    groups: wheel, libvirt
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048
