---
- name: Update All Debian Family Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Packages on all OS
  ansible.builtin.package:
    name:
      - cargo
      - conky
      - curl
      - fd-find
      - git
      - nmap
      - ripgrep
      - tmux
      - vim
      - wget
      - zsh
    state: latest

- name: Check if YADM is installed
  ansible.builtin.stat:
    path: /usr/local/bin/yadm
  register: yadm

- name: Install YADM
  ansible.builtin.command: curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm
  when: yadm.stat.exists == False

- name: Make YADM Executable
  ansible.builtin.command: chmod a+x /usr/local/bin/yadm
  when: yadm.stat.exists == False

- name: Add/Configure user Absenth
  ansible.builtin.user:
    name: absenth
    comment: Absenth 762
    groups: sudo
    shell: /bin/zsh
    generate_ssh_key: yes
    ssh_key_bits: 2048